//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCOMSYSTEM.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INCOMSYSTEMEntities : DbContext
    {
        public INCOMSYSTEMEntities()
            : base("name=INCOMSYSTEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chats> Chats { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<LegalForms> LegalForms { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Specializations> Specializations { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<UsersDetail> UsersDetail { get; set; }
        public virtual DbSet<SpecializationsEmployee> SpecializationsEmployee { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
    }
}
