//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCOMSYSTEM.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public long id { get; set; }
        public long idChat { get; set; }
        public long idUser { get; set; }
        public string message { get; set; }
        public System.DateTime dateSend { get; set; }
        public Nullable<long> idFile { get; set; }
    
        public virtual Chats Chats { get; set; }
        public virtual HistoryUploaded HistoryUploaded { get; set; }
        public virtual UsersDetail UsersDetail { get; set; }

        public string shortMessage => message.Length > 125 ? message.Substring(0, 125) + "..." : message;
    }
}
