//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCOMSYSTEM.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public long id { get; set; }
        public long idChat { get; set; }
        public string message { get; set; }
        public byte[] attachment { get; set; }
        public System.DateTime dateSend { get; set; }
    
        public virtual Chats Chats { get; set; }
    }
}
