//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCOMSYSTEM.Context
{
    using System;
    using System.Windows;
    using System.Collections.Generic;
    using INCOMSYSTEM.Windows;
    
    public partial class Orders
    {
        public long id { get; set; }
        public long idCustomer { get; set; }
        public Nullable<long> idExecutor { get; set; }
        public long idTask { get; set; }
        public decimal price { get; set; }
        public double difficulty { get; set; }
        public System.DateTime dateOrder { get; set; }
        public Nullable<System.DateTime> planDateStart { get; set; }
        public Nullable<System.DateTime> factDateStart { get; set; }
        public Nullable<System.DateTime> planDateComplete { get; set; }
        public Nullable<System.DateTime> factDateComplete { get; set; }
        public byte[] attachment { get; set; }
        public string fileExtension { get; set; }
        public byte idStatus { get; set; }
    
        public virtual Chats Chats { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Tasks Tasks { get; set; }

        public Visibility CanJoinChat =>
            Chats.idManager == null || MainWindow.AuthUser?.idUser == Chats.idManager
                ? Visibility.Visible
                : Visibility.Collapsed;

        public Visibility CanFormAgreement =>
            idExecutor != null && planDateStart != null && planDateComplete != null
                ? Visibility.Visible
                : Visibility.Collapsed;
    }
}
