//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCOMSYSTEM.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecializationsEmployee
    {
        public long id { get; set; }
        public long idEmployee { get; set; }
        public int idSpecialization { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Specializations Specializations { get; set; }
    }
}
