//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCOMSYSTEM.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdatesHistory
    {
        public UpdatesHistory()
        {
            id = System.Guid.NewGuid();
        }
        
        public System.Guid id { get; set; }
        public string tableName { get; set; }
        public long idRecord { get; set; }
        public string field { get; set; }
        public string oldValue { get; set; }
        public string newValue { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public byte idStatus { get; set; }
        public Nullable<long> idUser { get; set; }
    
        public virtual StatusesUpdate StatusesUpdate { get; set; }
        public virtual UsersDetail UsersDetail { get; set; }
    }
}
